// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Protos/Customers.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from Protos/Customers.proto</summary>
public static partial class CustomersReflection {

  #region Descriptor
  /// <summary>File descriptor for Protos/Customers.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static CustomersReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChZQcm90b3MvQ3VzdG9tZXJzLnByb3RvGh5nb29nbGUvcHJvdG9idWYvd3Jh",
          "cHBlcnMucHJvdG8iZAokSXNQcm9kdWN0QWRkcmVzc1VwZGF0ZUFsbG93ZWRS",
          "ZXF1ZXN0EhIKCnN0YXRlX0Zyb20YASABKAkSEAoIc3RhdGVfVG8YAiABKAkS",
          "FgoOdXNlcnJlbGF0aW9uaWQYAyABKAUijgEKJUlzUHJvZHVjdEFkZHJlc3NV",
          "cGRhdGVBbGxvd2VkUmVzcG9uc2USFQoNUmV0dXJuTWVzc2FnZRgCIAEoCRI0",
          "ChBBZGRyZXNzVXBkYXRhYmxlGAMgASgLMhouZ29vZ2xlLnByb3RvYnVmLkJv",
          "b2xWYWx1ZUoECAEQAlISSXNBZGRyZXNzVXBkYXRhYmxlMnoKCEN1c3RvbWVy",
          "Em4KHUlzUHJvZHVjdEFkZHJlc3NVcGRhdGVBbGxvd2VkEiUuSXNQcm9kdWN0",
          "QWRkcmVzc1VwZGF0ZUFsbG93ZWRSZXF1ZXN0GiYuSXNQcm9kdWN0QWRkcmVz",
          "c1VwZGF0ZUFsbG93ZWRSZXNwb25zZWIGcHJvdG8z"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.WrappersReflection.Descriptor, },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::IsProductAddressUpdateAllowedRequest), global::IsProductAddressUpdateAllowedRequest.Parser, new[]{ "StateFrom", "StateTo", "Userrelationid" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::IsProductAddressUpdateAllowedResponse), global::IsProductAddressUpdateAllowedResponse.Parser, new[]{ "ReturnMessage", "AddressUpdatable" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class IsProductAddressUpdateAllowedRequest : pb::IMessage<IsProductAddressUpdateAllowedRequest> {
  private static readonly pb::MessageParser<IsProductAddressUpdateAllowedRequest> _parser = new pb::MessageParser<IsProductAddressUpdateAllowedRequest>(() => new IsProductAddressUpdateAllowedRequest());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<IsProductAddressUpdateAllowedRequest> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::CustomersReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public IsProductAddressUpdateAllowedRequest() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public IsProductAddressUpdateAllowedRequest(IsProductAddressUpdateAllowedRequest other) : this() {
    stateFrom_ = other.stateFrom_;
    stateTo_ = other.stateTo_;
    userrelationid_ = other.userrelationid_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public IsProductAddressUpdateAllowedRequest Clone() {
    return new IsProductAddressUpdateAllowedRequest(this);
  }

  /// <summary>Field number for the "state_From" field.</summary>
  public const int StateFromFieldNumber = 1;
  private string stateFrom_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string StateFrom {
    get { return stateFrom_; }
    set {
      stateFrom_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "state_To" field.</summary>
  public const int StateToFieldNumber = 2;
  private string stateTo_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string StateTo {
    get { return stateTo_; }
    set {
      stateTo_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "userrelationid" field.</summary>
  public const int UserrelationidFieldNumber = 3;
  private int userrelationid_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int Userrelationid {
    get { return userrelationid_; }
    set {
      userrelationid_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as IsProductAddressUpdateAllowedRequest);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(IsProductAddressUpdateAllowedRequest other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (StateFrom != other.StateFrom) return false;
    if (StateTo != other.StateTo) return false;
    if (Userrelationid != other.Userrelationid) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (StateFrom.Length != 0) hash ^= StateFrom.GetHashCode();
    if (StateTo.Length != 0) hash ^= StateTo.GetHashCode();
    if (Userrelationid != 0) hash ^= Userrelationid.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (StateFrom.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(StateFrom);
    }
    if (StateTo.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(StateTo);
    }
    if (Userrelationid != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(Userrelationid);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (StateFrom.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(StateFrom);
    }
    if (StateTo.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(StateTo);
    }
    if (Userrelationid != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Userrelationid);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(IsProductAddressUpdateAllowedRequest other) {
    if (other == null) {
      return;
    }
    if (other.StateFrom.Length != 0) {
      StateFrom = other.StateFrom;
    }
    if (other.StateTo.Length != 0) {
      StateTo = other.StateTo;
    }
    if (other.Userrelationid != 0) {
      Userrelationid = other.Userrelationid;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          StateFrom = input.ReadString();
          break;
        }
        case 18: {
          StateTo = input.ReadString();
          break;
        }
        case 24: {
          Userrelationid = input.ReadInt32();
          break;
        }
      }
    }
  }

}

public sealed partial class IsProductAddressUpdateAllowedResponse : pb::IMessage<IsProductAddressUpdateAllowedResponse> {
  private static readonly pb::MessageParser<IsProductAddressUpdateAllowedResponse> _parser = new pb::MessageParser<IsProductAddressUpdateAllowedResponse>(() => new IsProductAddressUpdateAllowedResponse());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<IsProductAddressUpdateAllowedResponse> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::CustomersReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public IsProductAddressUpdateAllowedResponse() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public IsProductAddressUpdateAllowedResponse(IsProductAddressUpdateAllowedResponse other) : this() {
    returnMessage_ = other.returnMessage_;
    AddressUpdatable = other.AddressUpdatable;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public IsProductAddressUpdateAllowedResponse Clone() {
    return new IsProductAddressUpdateAllowedResponse(this);
  }

  /// <summary>Field number for the "ReturnMessage" field.</summary>
  public const int ReturnMessageFieldNumber = 2;
  private string returnMessage_ = "";
  /// <summary>
  /// bool IsAddressUpdatable = 1;
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string ReturnMessage {
    get { return returnMessage_; }
    set {
      returnMessage_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "AddressUpdatable" field.</summary>
  public const int AddressUpdatableFieldNumber = 3;
  private static readonly pb::FieldCodec<bool?> _single_addressUpdatable_codec = pb::FieldCodec.ForStructWrapper<bool>(26);
  private bool? addressUpdatable_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool? AddressUpdatable {
    get { return addressUpdatable_; }
    set {
      addressUpdatable_ = value;
    }
  }


  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as IsProductAddressUpdateAllowedResponse);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(IsProductAddressUpdateAllowedResponse other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (ReturnMessage != other.ReturnMessage) return false;
    if (AddressUpdatable != other.AddressUpdatable) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (ReturnMessage.Length != 0) hash ^= ReturnMessage.GetHashCode();
    if (addressUpdatable_ != null) hash ^= AddressUpdatable.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (ReturnMessage.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(ReturnMessage);
    }
    if (addressUpdatable_ != null) {
      _single_addressUpdatable_codec.WriteTagAndValue(output, AddressUpdatable);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (ReturnMessage.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(ReturnMessage);
    }
    if (addressUpdatable_ != null) {
      size += _single_addressUpdatable_codec.CalculateSizeWithTag(AddressUpdatable);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(IsProductAddressUpdateAllowedResponse other) {
    if (other == null) {
      return;
    }
    if (other.ReturnMessage.Length != 0) {
      ReturnMessage = other.ReturnMessage;
    }
    if (other.addressUpdatable_ != null) {
      if (addressUpdatable_ == null || other.AddressUpdatable != false) {
        AddressUpdatable = other.AddressUpdatable;
      }
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 18: {
          ReturnMessage = input.ReadString();
          break;
        }
        case 26: {
          bool? value = _single_addressUpdatable_codec.Read(input);
          if (addressUpdatable_ == null || value != false) {
            AddressUpdatable = value;
          }
          break;
        }
      }
    }
  }

}

#endregion


#endregion Designer generated code
